### ISSUE TITLE
Milestone 1 - Canvas submission

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#4]
- [x] Include the URL of your public project’s repository in your milestone 1 submission on Canvas
- [x] Include the URL to this release (0.0.1) in your milestone 1 submission on Canvas
- [x] Pasting teamwork contract into the text box for your Canvas homework submission for this milestone
