### ISSUE TITLE
Milestone 3: Work allocation

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#40]
Hi @ytz @arijc76 

I just reviewed milestone 3.  Here's a summary of whats required:

- [ ] Makefile driver script
- [ ] Review/address feedback from TAs and peers
- [ ] Iterate on project 

Let me know how you guys want to split the work up this week.  Maybe for the iteration/feedback part we can shuffle around the sections to give everyone the chance to work on different parts of the project.

**Comment by nicovandenhooff** [comment]
separate issues have been opened
