### ISSUE TITLE
Milestone 1 improvement recommendations from Florencia

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#51]
Original recommendations from Florencia are in [these slides:](https://pages.github.ubc.ca/fdandrea/DSCI-522_milestone3/slides.html#31).  Creating an issue so we can remember to update for them.

- [x] License file: _(update copyright holder to be our names)_
- [x] Code of conduct: _add an email (I don't think we should put our personal emails... maybe we can use our UBC emails?)_
- [x] Figure captions: _(we already have explanations, we could add figure #'s and explicit captions?)_
- [x] Abstract/summary in report _(we could add this as the first page in our Jupyter book?)_

Adding the below as well:

- [x] Update README to be in line with milestone 3

**Comment by ytz** [comment]
I can do the license and code of conduct first. Using our UBC emails is a good idea. @nicovandenhooff @arijc76 , what is your UBC email?

* ytzify@student.ubc.ca
* njvdh@student.ubc.ca
* arijc@student.ubc.ca

_Update: See #53_

We can do figure captions and abstract/summary once we are finished editing our report for milestone 3.

**Comment by arijeetchatterjee** [comment]
My ubc mail - arijc@student.ubc.ca

**Comment by nicovandenhooff** [comment]
added my email above

**Comment by nicovandenhooff** [comment]
Also sounds good re: fig caption/abstract

**Comment by nicovandenhooff** [comment]
@ytz @arijc76 I couldn't figure out how to add figure captions in the `.ipynb` files... I tried the syntax Ari had in the slack channel but it didn't work.  Also there was no documentation on how to do so on the Jupyter Book site unfortunately (it only talks about how to do so with `.md` files).

**Comment by arijeetchatterjee** [comment]
Yes, that syntax was for `.md` files. Not sure if captions work in `.ipynb` files.

**Comment by nicovandenhooff** [comment]
Yeah based off my research I don't think they do.  We can probably just leave them out for the `.ipynb` files then.

**Comment by nicovandenhooff** [comment]
Closing this issue since the abstract/summary is noted in Issue #72 now
