### ISSUE TITLE
Milestone 4: Tasks

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#67]
Summary of tasks required for [milestone 4](https://pages.github.ubc.ca/mds-2021-22/DSCI_522_dsci-workflows_students/materials/assignments/milestone4.html)

**Makefile Graph**
- [x] Create Makefile dependency diagram and add to `README.md` in root directory

**Wrap project in a Docker container, which involves**
- [x] Write Dockerfile and include in root directory
- [x] Use GitHub Actions to build Docker image
- [x] Do not include data or code in Docker image
- [x] Include instructions in `README` for how to use project `with` Docker
- [x] Include instructions in `README` for how to use project `without` Docker (already done)

**Comment by nicovandenhooff** [comment]
@ytz @arijc76 I've generated the dependency graph for our `Makefile` - are you guys okay if I add a pull request for this and you can review to check if its okay?

**Comment by nicovandenhooff** [comment]
All completed
